create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table product (price numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table test (test numeric(38,2) not null, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table associations (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table wastes_types (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, city varchar(255) not null, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, volunteer_id integer not null, id bigint generated by default as identity, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, volunteer_id bigint, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
alter table if exists volunteers add constraint FKcx13qixfv4jlp0xht1r0hkk3w foreign key (volunteer_id) references collect;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table city (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists city add constraint FK5jxox2iavxlejmsvtsjwtpvpk foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKr2oe5i0gmuvbgyjsa6q8w9gor foreign key (coordinates_id) references city;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinate (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FK9p4nr0cqtq6fml0of9s4gvenm foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinate add constraint FKb457buef95xyon2or3f4pg3yp foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collect (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FK9p4nr0cqtq6fml0of9s4gvenm foreign key (city_id) references collect;
alter table if exists collect add constraint FK9jxq80iy0aq2qwj1gmghvbxym foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;

    create table association (
        points integer not null,
        id bigint generated by default as identity,
        description varchar(255) not null,
        image varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table cities (
        city_id bigint,
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table collects (
        butt_nb integer not null,
        date date not null,
        electronics_nb integer not null,
        glass_nb integer not null,
        others_nb integer not null,
        plastic_nb integer not null,
        city_id bigint not null,
        id bigint generated by default as identity,
        volunteer_id bigint,
        primary key (id)
    );

    create table coordinates (
        latitude float4 not null,
        longitude float4 not null,
        coordinates_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table volunteers (
        created_at date not null,
        donation_points integer not null,
        total_points integer not null,
        updated_at date,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        firstname varchar(255) not null,
        lastname varchar(255) not null,
        location varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create table waste_type (
        id bigint generated by default as identity,
        class_name varchar(255) not null,
        label varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    alter table if exists cities 
       add constraint FKpgbyxpyiyktx7huu8xttilxy7 
       foreign key (city_id) 
       references collects;

    alter table if exists collects 
       add constraint FKb99e5cbiop2gchpw22mrshydm 
       foreign key (city_id) 
       references cities;

    alter table if exists collects 
       add constraint FK7wdvq27imvrgu79sxub00bed 
       foreign key (volunteer_id) 
       references volunteers;

    alter table if exists coordinates 
       add constraint FK8ta469uvt7gcbtyd6vg5037kh 
       foreign key (coordinates_id) 
       references cities;

    create table association (
        points integer not null,
        id bigint generated by default as identity,
        description varchar(255) not null,
        image varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table cities (
        city_id bigint,
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table collects (
        butt_nb integer not null,
        date date not null,
        electronics_nb integer not null,
        glass_nb integer not null,
        others_nb integer not null,
        plastic_nb integer not null,
        city_id bigint not null,
        id bigint generated by default as identity,
        volunteer_id bigint,
        primary key (id)
    );

    create table coordinates (
        latitude float4 not null,
        longitude float4 not null,
        coordinates_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table volunteers (
        created_at date not null,
        donation_points integer not null,
        total_points integer not null,
        updated_at date,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        firstname varchar(255) not null,
        lastname varchar(255) not null,
        location varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create table waste_type (
        id bigint generated by default as identity,
        class_name varchar(255) not null,
        label varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    alter table if exists cities 
       add constraint FKpgbyxpyiyktx7huu8xttilxy7 
       foreign key (city_id) 
       references collects;

    alter table if exists collects 
       add constraint FKb99e5cbiop2gchpw22mrshydm 
       foreign key (city_id) 
       references cities;

    alter table if exists collects 
       add constraint FK7wdvq27imvrgu79sxub00bed 
       foreign key (volunteer_id) 
       references volunteers;

    alter table if exists coordinates 
       add constraint FK8ta469uvt7gcbtyd6vg5037kh 
       foreign key (coordinates_id) 
       references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FKpgbyxpyiyktx7huu8xttilxy7 foreign key (city_id) references collects;
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FKpgbyxpyiyktx7huu8xttilxy7 foreign key (city_id) references collects;
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FKpgbyxpyiyktx7huu8xttilxy7 foreign key (city_id) references collects;
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FKpgbyxpyiyktx7huu8xttilxy7 foreign key (city_id) references collects;
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (city_id bigint, id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists cities add constraint FKpgbyxpyiyktx7huu8xttilxy7 foreign key (city_id) references collects;
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, coordinates_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FK8ta469uvt7gcbtyd6vg5037kh foreign key (coordinates_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
create table association (points integer not null, id bigint generated by default as identity, description varchar(255) not null, image varchar(255) not null, name varchar(255) not null, primary key (id));
create table cities (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
create table collects (butt_nb integer not null, date date not null, electronics_nb integer not null, glass_nb integer not null, others_nb integer not null, plastic_nb integer not null, city_id bigint not null, id bigint generated by default as identity, volunteer_id bigint, primary key (id));
create table coordinates (latitude float4 not null, longitude float4 not null, city_id bigint, id bigint generated by default as identity, primary key (id));
create table volunteers (created_at date not null, donation_points integer not null, total_points integer not null, updated_at date, id bigint generated by default as identity, email varchar(255) not null unique, firstname varchar(255) not null, lastname varchar(255) not null, location varchar(255) not null, password varchar(255) not null, primary key (id));
create table waste_type (id bigint generated by default as identity, class_name varchar(255) not null, label varchar(255) not null, value varchar(255) not null, primary key (id));
alter table if exists collects add constraint FKb99e5cbiop2gchpw22mrshydm foreign key (city_id) references cities;
alter table if exists collects add constraint FK7wdvq27imvrgu79sxub00bed foreign key (volunteer_id) references volunteers;
alter table if exists coordinates add constraint FKpkll11usrngc8p8uspycyfyy6 foreign key (city_id) references cities;
